export default {
      null: '',
      'what-to-do': 'Send the link to the other party',
      'us-ban-maps': 'ban a map',
      'us-pick-maps': 'pick a map',
      'us-ban-champs': 'ban a champ',
      'us-pick-champs': 'pick a champ',
      'them-ban-maps': 'wait for opponent map ban',
      'them-pick-maps': 'wait for opponent map pick',
      'them-ban-champs': 'wait for opponent champ ban',
      'them-pick-champs': 'wait for opponent champ pick',
      'null-null-done': 'gl & hf',
      'undefined-undefined-undefined': ' ',
      'awoken': 'Awoken',
      'blood_covenant': 'Blood Covenant',
      'blood_run': 'Blood Run',
      'burial_chamber': 'Burial Chamber',
      'church': 'Church of Azathoth',
      'corrupted_keep': 'Corrupted Keep',
      'dark_zone': 'The Dark Zone',
      'deep_embrace': 'Deep embrace',
      'exile': 'Exile',
      'insomnia': 'Insomnia',
      'lockbox': 'Lockbox',
      'longest_yard': 'Longest Yard',
      'ruins_of_sarnath': 'Ruins of Sarnath',
      'tempest_shrine': 'Tempest Shrine',
      'the_molten_falls': 'Molten Falls',
      'tower_of_koth': 'Tower of Koth',
      'vale_of_pnath': 'Vale of Pnath',
      'anarki': 'Anarki',
      'athena': 'Athena',
      'bj': 'BJ Blazkowicz',
      'clutch': 'Clutch',
      'death_knight': 'Death Knight',
      'doom': 'DOOM Slayer',
      'eisen': 'Eisen',
      'galena': 'Galena',
      'keel': 'Keel',
      'nyx': 'Nyx',
      'ranger': 'Ranger',
      'scalebearer': 'Scalebearer',
      'slash': 'Slash',
      'sorlag': 'Sorlag',
      'strogg': 'Strogg & Peeker',
      'visor': 'Visor'
};
